# RRvGO report-product discovery and status ---------------------------------
#
# The biological report must consume semantic products generated by the
# pipeline/validation run. It must not recompute RRvGO while knitting and it
# must not hide valid sidecar products merely because a compatibility renderer
# omitted run_rrvgo metadata.

.echogo_first_nonempty <- function(x, fallback = NA_character_) {
  x <- as.character(x)
  x <- x[!is.na(x) & nzchar(trimws(x))]
  if (length(x)) x[[1]] else fallback
}

.echogo_rrvgo_product_from_path <- function(path, tab = NULL) {
  if (!is.null(tab) && is.data.frame(tab) && "semantic_product" %in% names(tab)) {
    value <- .echogo_first_nonempty(tab$semantic_product)
    if (!is.na(value)) return(value)
  }
  low <- tolower(gsub("\\\\", "/", path))
  if (grepl("alternative_context_hypothesis", low, fixed = TRUE)) {
    return("alternative_context_hypothesis")
  }
  if (grepl("target_supported", low, fixed = TRUE)) return("target_supported")
  NA_character_
}

.echogo_rrvgo_ontology_from_path <- function(path, tab = NULL) {
  if (!is.null(tab) && is.data.frame(tab) && "ontology" %in% names(tab)) {
    value <- toupper(.echogo_first_nonempty(tab$ontology))
    if (!is.na(value) && value %in% c("BP", "MF", "CC")) return(value)
  }
  base <- basename(path)
  hit <- regexec("rrvgo_(BP|MF|CC)_clusters\\.csv$", base, ignore.case = TRUE)
  match <- regmatches(base, hit)[[1]]
  if (length(match) >= 2L) toupper(match[[2]]) else NA_character_
}

.echogo_rrvgo_allowed_ids <- function(evidence, product) {
  if (is.null(evidence) || !is.data.frame(evidence) || !nrow(evidence)) return(character())
  if (identical(product, "target_supported")) {
    return(unique(as.character(evidence$term_id[
      evidence$evidence_profile %in% c("TARGET_ONLY", "TARGET_PLUS_CONTEXT")
    ])))
  }
  if (identical(product, "alternative_context_hypothesis")) {
    return(unique(as.character(evidence$term_id[
      evidence$evidence_profile %in% "ALTERNATIVE_CONTEXT"
    ])))
  }
  character()
}

.echogo_read_rrvgo_clusters <- function(path) {
  tryCatch(
    readr::read_csv(path, show_col_types = FALSE),
    error = function(e) tibble::tibble()
  )
}

.echogo_discover_rrvgo_products <- function(rrvgo_dir, evidence,
                                            configuration = list()) {
  configured <- isTRUE(configuration$run_rrvgo)
  cluster_files <- if (dir.exists(rrvgo_dir)) {
    list.files(
      rrvgo_dir,
      pattern = "rrvgo_(BP|MF|CC)_clusters\\.csv$",
      recursive = TRUE,
      full.names = TRUE,
      ignore.case = TRUE
    )
  } else {
    character()
  }

  rows <- lapply(cluster_files, function(path) {
    tab <- .echogo_read_rrvgo_clusters(path)
    product <- .echogo_rrvgo_product_from_path(path, tab)
    ontology <- .echogo_rrvgo_ontology_from_path(path, tab)
    ids <- if ("go" %in% names(tab)) {
      unique(as.character(tab$go))
    } else if ("term_id" %in% names(tab)) {
      unique(as.character(tab$term_id))
    } else {
      character()
    }
    ids <- ids[!is.na(ids) & nzchar(ids)]
    allowed <- .echogo_rrvgo_allowed_ids(evidence, product)
    evidence_match <- length(ids) > 0L && length(allowed) > 0L && all(ids %in% allowed)

    tibble::tibble(
      semantic_product = product,
      ontology = ontology,
      cluster_file = normalizePath(path, winslash = "/", mustWork = FALSE),
      cluster_row_n = nrow(tab),
      evidence_match = evidence_match,
      semantic_reference_orgdb = if ("semantic_reference_orgdb" %in% names(tab)) {
        .echogo_first_nonempty(tab$semantic_reference_orgdb)
      } else NA_character_,
      semantic_reference_role = if ("semantic_reference_role" %in% names(tab)) {
        .echogo_first_nonempty(tab$semantic_reference_role)
      } else NA_character_,
      semantic_method = if ("semantic_method" %in% names(tab)) {
        .echogo_first_nonempty(tab$semantic_method, "Rel")
      } else "Rel",
      status = if (evidence_match) "GENERATED" else "REJECTED_EVIDENCE_MISMATCH"
    )
  })
  products <- dplyr::bind_rows(rows)
  valid <- if (nrow(products)) {
    dplyr::filter(products, .data$status == "GENERATED", .data$evidence_match %in% TRUE)
  } else {
    tibble::tibble()
  }

  configured_orgdb <- .echogo_first_nonempty(configuration$semantic_reference_orgdb)
  configured_role <- .echogo_first_nonempty(configuration$semantic_reference_role)
  configured_method <- .echogo_first_nonempty(configuration$semantic_method, "Rel")
  inferred_orgdb <- if (nrow(valid)) .echogo_first_nonempty(valid$semantic_reference_orgdb) else NA_character_
  inferred_role <- if (nrow(valid)) .echogo_first_nonempty(valid$semantic_reference_role) else NA_character_
  inferred_method <- if (nrow(valid)) .echogo_first_nonempty(valid$semantic_method, "Rel") else "Rel"

  enabled <- configured || nrow(valid) > 0L
  state <- if (configured) {
    "REQUESTED_BY_RUN_CONFIGURATION"
  } else if (nrow(valid) > 0L) {
    "DISCOVERED_MATCHING_SIDECARS"
  } else {
    "DISABLED_OR_NO_MATCHING_PRODUCTS"
  }

  list(
    enabled = enabled,
    configured = configured,
    state = state,
    products = products,
    valid_products = valid,
    cluster_files = if (nrow(valid)) valid$cluster_file else character(),
    semantic_reference_orgdb = if (!is.na(configured_orgdb)) configured_orgdb else inferred_orgdb,
    semantic_reference_role = if (!is.na(configured_role)) configured_role else inferred_role,
    semantic_method = if (!is.na(configured_method) && configured) configured_method else inferred_method
  )
}

.echogo_rrvgo_status_row <- function(semantic_product, ontology, status,
                                     reason = NA_character_, input_term_n = NA_integer_,
                                     valid_term_n = NA_integer_,
                                     semantic_reference_orgdb = NA_character_,
                                     semantic_reference_role = NA_character_,
                                     semantic_method = "Rel",
                                     cluster_file = NA_character_) {
  tibble::tibble(
    semantic_product = as.character(semantic_product),
    ontology = as.character(ontology),
    status = as.character(status),
    reason = as.character(reason),
    input_term_n = as.integer(input_term_n),
    valid_term_n = as.integer(valid_term_n),
    semantic_reference_orgdb = as.character(semantic_reference_orgdb),
    semantic_reference_role = as.character(semantic_reference_role),
    semantic_method = as.character(semantic_method),
    cluster_file = as.character(cluster_file)
  )
}

.echogo_write_rrvgo_status <- function(status_rows, rrvgo_dir) {
  dir.create(rrvgo_dir, recursive = TRUE, showWarnings = FALSE)
  tab <- dplyr::bind_rows(status_rows)
  path <- file.path(rrvgo_dir, "rrvgo_product_status.csv")
  readr::write_csv(tab, path)
  invisible(path)
}

.echogo_read_rrvgo_status <- function(rrvgo_dir) {
  path <- file.path(rrvgo_dir, "rrvgo_product_status.csv")
  if (!file.exists(path)) return(tibble::tibble())
  tryCatch(readr::read_csv(path, show_col_types = FALSE), error = function(e) tibble::tibble())
}

.echogo_upsert_rrvgo_status <- function(status_rows, rrvgo_dir) {
  incoming <- dplyr::bind_rows(status_rows)
  if (!nrow(incoming)) return(invisible(file.path(rrvgo_dir, "rrvgo_product_status.csv")))
  existing <- .echogo_read_rrvgo_status(rrvgo_dir)
  combined <- dplyr::bind_rows(existing, incoming)
  if (all(c("semantic_product", "ontology") %in% names(combined))) {
    combined <- combined |>
      dplyr::mutate(.echogo_status_order = dplyr::row_number()) |>
      dplyr::group_by(.data$semantic_product, .data$ontology) |>
      dplyr::slice_max(.data$.echogo_status_order, n = 1L, with_ties = FALSE) |>
      dplyr::ungroup() |>
      dplyr::select(-.data$.echogo_status_order)
  }
  .echogo_write_rrvgo_status(combined, rrvgo_dir)
}

.echogo_rrvgo_status_message <- function(status_row) {
  if (is.null(status_row) || !is.data.frame(status_row) || !nrow(status_row)) {
    return("No RRvGO status was recorded for this ontology.")
  }
  d <- status_row[1, , drop = FALSE]
  status <- as.character(d$status[[1]])
  reason <- if ("reason" %in% names(d)) .echogo_first_nonempty(d$reason) else NA_character_
  if (identical(status, "GENERATED")) {
    return("Semantic reduction was generated for this ontology.")
  }
  if (grepl("^SKIPPED_", status)) {
    detail <- if (!is.na(reason)) paste0(" ", reason) else ""
    return(paste0("Semantic reduction was not generated for this ontology because the available input was insufficient.", detail))
  }
  if (identical(status, "DISABLED")) return("RRvGO semantic reduction was disabled for this run.")
  detail <- if (!is.na(reason)) paste0(" Reason: ", reason) else ""
  paste0("RRvGO status: ", status, ".", detail)
}
